In [1]:
import numpy as np
ar1=np.arange(13)


In [2]:
ar1
len(ar1)

13

In [6]:
reshaped_array=ar1.reshape(1,13)
reshaped_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#identity matrix can br created using two functions
#eye()-->used to define both user defined rows and columns
#identity()-->used to define same no. of rows and columns
#syntax-->np.identity(5)--> 5 is 5 rows and 5 columnns
#syntax-->np.eye(3,4)-->3 rows and 4 columns

In [10]:
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [11]:
ar2=np.arange(25)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
#to perform multidimensional slicing
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
ar2.shape

(5, 5)

In [15]:
#ar2[rows,columns,step]
ar2[0:3]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [19]:
ar2[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [20]:
ar2[2:3,2:3]

array([[12]])

In [21]:
ar2[-1]

array([20, 21, 22, 23, 24])

In [26]:
ar2[-2::-3,-2::-3]

array([[18, 15],
       [ 3,  0]])

In [27]:
ar2[-1::-4,-1::-4]

array([[24, 20],
       [ 4,  0]])

In [28]:
ar2[::-4,::-4]

array([[24, 20],
       [ 4,  0]])

In [29]:
ar2[-1:-4,-1:-4]

array([], shape=(0, 0), dtype=int32)

In [30]:
ar2[-4:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [32]:
ar3=np.arange(50).reshape(5,10)

In [33]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
np.sum(ar3)

1225

In [36]:
np.sum(ar3,axis=0)#to add based on column wise

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [37]:
np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [39]:
#mean-->average
#median-->center value
#mode-->max no. of repeated elements
#variance-->median /total no. of elements
#std-->square root of variance

In [41]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [43]:
#linspace
#it is used to print evenly seperated point between 2 range of values
#linspace(start,end,no. of parts)
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [44]:
np.linspace(1,10,3,dtype=int)

array([ 1,  5, 10])

In [45]:
np.linspace(1,10,3,retstep=True)

(array([ 1. ,  5.5, 10. ]), 4.5)

In [46]:
#random module
#np.random.randint(start,end)
#to generate random no. between the range
np.random.randint(40)

18

In [48]:
np.random.randint(10,40)

31

In [49]:
np.random.randint(1,50,6)

array([ 4, 24, 32, 25, 47,  6])

In [50]:
#rand-->to get randomly generated values from 0 to 1 based on uniform distribution
np.random.rand(5)

array([0.52884281, 0.12701316, 0.63222098, 0.11842296, 0.40548402])

In [2]:
import numpy as np
np.random.randn(5)

array([-0.79998607, -1.08270386, -1.02824557, -0.59495293,  1.26501044])

In [3]:
np.random.randn(4,5)

array([[-0.81787216, -1.2681022 , -0.66194439,  0.89139535,  0.40766993],
       [ 0.73932358,  0.89598607,  0.01306972, -1.52232417,  2.36774731],
       [ 0.26698403,  0.66246992, -1.61752954,  0.02273063, -1.04087386],
       [ 1.03890713, -0.76203344, -0.73488387, -0.400991  , -0.63411379]])

In [5]:
ar3=np.arange(50).reshape(5,10)
ar3.min()

0

In [6]:
ar3.max()

49

In [7]:
l1=[56,89,9,67,45]
np1=np.array(l1)
print(np1.argmin())
print(np1.argmax())
#argmin()-->to find the min value index position in an array
#argmax()-->to find the min value index position in an array

2
1


In [8]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.41211849, -0.85551998,  0.85090352])

In [9]:
np.sin(np1)
np.cos(np1)
np.tan(np1)


array([-0.61127369,  1.68582537, -0.45231566,  1.65231726,  1.61977519])

In [10]:
np.sin(np1)/np.cos(np1)

array([-0.61127369,  1.68582537, -0.45231566,  1.65231726,  1.61977519])

In [22]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1*4)+(2*5)+(3*6)=4+10+18=>32
np2*np3


array([ 4, 10, 18])

In [23]:
np4=np2*np3

In [15]:
sum(np4)

32

In [24]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(["t","ln1","ln2"])
#fname.tostring()

In [29]:
np2=np.array([1,2,3,8])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum(np2*np3)    
  


40

In [32]:
np1=np.array([1,2,3,4,np.nan,np.nan])
np1[np.isnan(np1)]

array([nan, nan])

In [33]:
np1[~np.isnan(np1)]

array([1., 2., 3., 4.])

In [5]:
import numpy as np
ini_array=np.array([[1,2,3],[45,4,7],[9,6,10]])
np.append(ini_array,[[12,23,45]],axis=0)

array([[ 1,  2,  3],
       [45,  4,  7],
       [ 9,  6, 10],
       [12, 23, 45]])

In [1]:
import pandas as pd
se=pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])
se.value_counts()

2    4
1    3
3    3
4    2
5    1
Name: count, dtype: int64

In [11]:
ser=pd.Series(np.random.randint(1,10,35))

In [12]:
df=ser.to_frame("name"=age)
df

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (2348543557.py, line 1)